/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;
import BDqueries.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
import java.awt.*;

        

/**
 *
 * @author Intech-Torreon
 */
public class Acceso extends javax.swing.JFrame {
    String usuario ="";
    String password = "";
    String actualFocus="";
    /**
     * Creates new form acceso
     */
    public Acceso() {
        initComponents();
       // deshabilita();
//
        this.setLocationRelativeTo(null);
        
          btnAcepta.setContentAreaFilled(false);
          btnCancela.setContentAreaFilled(false);
          btnSalir.setContentAreaFilled(false);

    }

      public void deshabilita(){
          btnCancela.setEnabled(false);
          btnAcepta.setEnabled(false);  
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn22 = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        btn00 = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btn66 = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        btn11 = new javax.swing.JButton();
        btn33 = new javax.swing.JButton();
        btn55 = new javax.swing.JButton();
        btn44 = new javax.swing.JButton();
        btn99 = new javax.swing.JButton();
        btn77 = new javax.swing.JButton();
        btn88 = new javax.swing.JButton();
        btnAcepta = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn22.setBackground(new java.awt.Color(255, 255, 0));
        btn22.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        btn22.setForeground(new java.awt.Color(255, 0, 0));
        btn22.setText("2");
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });
        getContentPane().add(btn22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 80, 50));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 51, 0));
        lblUsuario.setText("Usuario :");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 140, -1));

        btn00.setBackground(new java.awt.Color(255, 255, 0));
        btn00.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        btn00.setForeground(new java.awt.Color(255, 0, 0));
        btn00.setText("0");
        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });
        getContentPane().add(btn00, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 80, 50));

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 51, 51));
        lblPassword.setText("Password :");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 160, -1));

        txtPassword.setBackground(new java.awt.Color(0, 0, 204));
        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 130, -1));

        btn66.setBackground(new java.awt.Color(255, 255, 0));
        btn66.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        btn66.setForeground(new java.awt.Color(255, 0, 0));
        btn66.setText("6");
        btn66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn66ActionPerformed(evt);
            }
        });
        getContentPane().add(btn66, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 80, 50));

        txtUsuario.setBackground(new java.awt.Color(0, 0, 204));
        txtUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 167, 120, -1));

        btn11.setBackground(new java.awt.Color(255, 255, 0));
        btn11.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        btn11.setForeground(new java.awt.Color(255, 0, 0));
        btn11.setText("1");
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        getContentPane().add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 80, 50));

        btn33.setBackground(new java.awt.Color(255, 255, 0));
        btn33.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        btn33.setForeground(new java.awt.Color(255, 0, 0));
        btn33.setText("3");
        btn33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn33ActionPerformed(evt);
            }
        });
        getContentPane().add(btn33, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 80, 50));

        btn55.setBackground(new java.awt.Color(255, 255, 0));
        btn55.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        btn55.setForeground(new java.awt.Color(255, 0, 0));
        btn55.setText("5");
        btn55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn55ActionPerformed(evt);
            }
        });
        getContentPane().add(btn55, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 80, 50));

        btn44.setBackground(new java.awt.Color(255, 255, 0));
        btn44.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        btn44.setForeground(new java.awt.Color(255, 0, 0));
        btn44.setText("4");
        btn44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn44ActionPerformed(evt);
            }
        });
        getContentPane().add(btn44, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 80, 50));

        btn99.setBackground(new java.awt.Color(255, 255, 0));
        btn99.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        btn99.setForeground(new java.awt.Color(255, 0, 0));
        btn99.setText("9");
        btn99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn99ActionPerformed(evt);
            }
        });
        getContentPane().add(btn99, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 80, 50));

        btn77.setBackground(new java.awt.Color(255, 255, 0));
        btn77.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        btn77.setForeground(new java.awt.Color(255, 0, 0));
        btn77.setText("7");
        btn77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn77ActionPerformed(evt);
            }
        });
        getContentPane().add(btn77, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 80, 50));

        btn88.setBackground(new java.awt.Color(255, 255, 0));
        btn88.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        btn88.setForeground(new java.awt.Color(255, 0, 0));
        btn88.setText("8");
        btn88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn88ActionPerformed(evt);
            }
        });
        getContentPane().add(btn88, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 80, 50));

        btnAcepta.setBackground(new java.awt.Color(255, 255, 0));
        btnAcepta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ok.png"))); // NOI18N
        btnAcepta.setToolTipText("Aceptar");
        btnAcepta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcepta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 80, 70));

        btnCancela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        btnCancela.setToolTipText("Borrar");
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancela, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 70, 70));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.jpg"))); // NOI18N
        btnSalir.setToolTipText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 90, 60));

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("LA GRANJITA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -50, 220, 250));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/granjita1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        // TODO add your handling code here:
         if(actualFocus=="user"){
                   usuario += "2";
              txtUsuario.setText(usuario); 
        }
         else {
               password += "2";
               txtPassword.setText(password);
        }       
    }//GEN-LAST:event_btn22ActionPerformed

    private void btn66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn66ActionPerformed
        // TODO add your handling code here:
         if(actualFocus=="user"){
                   usuario += "6";
              txtUsuario.setText(usuario); 
        }
         else {
               password += "6";
               txtPassword.setText(password);
        }       
    }//GEN-LAST:event_btn66ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        // TODO add your handling code here:
        if(actualFocus=="user"){
                   usuario += "1";
              txtUsuario.setText(usuario); 
        }
         else {
               password += "1";
               txtPassword.setText(password);
        }
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn33ActionPerformed
        // TODO add your handling code here:
         if(actualFocus=="user"){
                   usuario += "3";
              txtUsuario.setText(usuario); 
        }
         else {
               password += "3";
               txtPassword.setText(password);
        }       
    }//GEN-LAST:event_btn33ActionPerformed

    private void btn44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn44ActionPerformed
        // TODO add your handling code here:
                if(actualFocus=="user"){
                   usuario += "4";
              txtUsuario.setText(usuario); 
        }
         else {
               password += "4";
               txtPassword.setText(password);
        }
    }//GEN-LAST:event_btn44ActionPerformed

    private void btn55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn55ActionPerformed
        // TODO add your handling code here:
         if(actualFocus=="user"){
                   usuario += "5";
              txtUsuario.setText(usuario); 
        }
         else {
               password += "5";
               txtPassword.setText(password);
        }       
    }//GEN-LAST:event_btn55ActionPerformed

    private void btn77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn77ActionPerformed
        // TODO add your handling code here:
        if(actualFocus=="user"){
                   usuario += "7";
              txtUsuario.setText(usuario); 
        }
         else {
               password += "7";
               txtPassword.setText(password);
        }        
    }//GEN-LAST:event_btn77ActionPerformed

    private void btn88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn88ActionPerformed
         if(actualFocus=="user"){
                   usuario += "8";
              txtUsuario.setText(usuario); 
        }
         else {
               password += "8";
               txtPassword.setText(password);
        }  
        // TODO add your handling code here:
    }//GEN-LAST:event_btn88ActionPerformed

    private void btn99ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn99ActionPerformed
         if(actualFocus=="user"){
                   usuario += "9";
              txtUsuario.setText(usuario); 
        }
         else {
               password += "9";
               txtPassword.setText(password);
        }  
        // TODO add your handling code here:
    }//GEN-LAST:event_btn99ActionPerformed

    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn00ActionPerformed
         if(actualFocus=="user"){
                   usuario += "0";
              txtUsuario.setText(usuario); 
        }
         else {
               password += "0";
               txtPassword.setText(password);
        }  
        // TODO add your handling code here:
    }//GEN-LAST:event_btn00ActionPerformed

    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        txtPassword.setText("");
        txtUsuario.setText("");
        password="";
        usuario="";
        txtUsuario.requestFocus();
       // deshabilita();
    }//GEN-LAST:event_btnCancelaActionPerformed

    private void btnAceptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptaActionPerformed
        // TODO add your handling code here:
 
        if(usuario==""){   // si usuario esta vacio
            JOptionPane.showMessageDialog(null,"Favor de introducir clave de usuario");
            txtUsuario.requestFocus();
          
        }
        if(password==""){   /// si password esta vacio
            JOptionPane.showMessageDialog(null,"Favor de introducir password");
            txtPassword.requestFocus();
        }
        if (usuario != "" && password != ""){
        //conectarse a la BD
        Conexion mysql = new Conexion();
        Connection link = mysql.conectarDB();
        String sSQL = "";
        String cve ="";
        String nom = "";
        String nivel = "";
        sSQL = "SELECT clave, nombre, tipo from usuario WHERE"
                + " clave = " + usuario + " AND contrasena = " + password;
         try{
            Statement st = link.createStatement();
            ResultSet rs = st.executeQuery(sSQL);
            
            while(rs.next()){
                cve = rs.getString("clave");
                nom = rs.getString("nombre");
                nivel = rs.getString("tipo");
            }
            if(cve.equals("")){
                JOptionPane.showMessageDialog(null,"Clave de Usuario o password incorrectos");
            } else{
               
                if(nivel.equals("Admin")){
                 Admin usuario = new Admin();
                 
                 usuario.nombreUsuario = nom;
                 usuario.claveUsuario=cve;
                 usuario.cambiarTitulo();
                 usuario.setVisible(true);                
                 dispose();
                }
                if(nivel.equals("Cajero")){
                 Cajero usuario = new Cajero();
                 
                 usuario.nombreCajero = nom;
                 usuario.claveCajero=cve;
                 usuario.cambiarTitulo();
                 usuario.setVisible(true);                
                 dispose();
                }
            } 
            
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null,ex);
        }
        }
    }//GEN-LAST:event_btnAceptaActionPerformed

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        // TODO add your handling code here:
         actualFocus = "user";
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        // TODO add your handling code here:
          //  System.out.println("usurio "+ usuario + "get text: "+ txtUsuario.getText());
            
           // btnCancela.setEnabled(true);
        
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
       actualFocus = "pass";
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
        //if(txtUsuario.getText() != null){
           // btnCancela.setEnabled(true);
            
       // }
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
         // if(txtPassword.getText()!= null){
         //   btnCancela.setEnabled(true);
       // }      
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceso().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn33;
    private javax.swing.JButton btn44;
    private javax.swing.JButton btn55;
    private javax.swing.JButton btn66;
    private javax.swing.JButton btn77;
    private javax.swing.JButton btn88;
    private javax.swing.JButton btn99;
    private javax.swing.JButton btnAcepta;
    private javax.swing.JButton btnCancela;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}
